# Makefile.AIX for swiggle
#
# $Id: Makefile.Linux,v 1.3 2003/10/22 21:01:19 le Exp $
CC = gcc
PROGRAM = swiggle
OBJS = swiggle.o resize.o html.o
HEADER = swiggle.h
CFLAGS = -Wall -I/usr/local/include -I/usr/local/include/libexif -DNO_D_TYPE
LDFLAGS = -L/usr/local/lib -ljpeg -lexif

all: ${PROGRAM}

${PROGRAM}: ${OBJS}
	gcc ${CFLAGS} ${LDFLAGS} -o ${PROGRAM} ${OBJS}

${OBJS}:

install:
	install -c -o 0 -g 0 -s swiggle /usr/local/bin

clean:
	rm -f *.o core ${PROGRAM}
